### ISSUE TITLE
Server setup todo

### ISSUE THREAD

**Issue by stefannorman** [stefannorman/ironmanstatistik#12]
- [ ] Lägg in admins
- [ ] Sätt upp cronjobb för importer
- [ ] Testa bilduppladdningen
- [ ] Flytta över bilder (race, club, athletes)
- [ ] Kör över db-datat igen.
- [ ] Testa http://ilsd.se:81
